public enum TipoToken {
    IDENTIFICADOR, NUMERO, CADENA,
    AND, DISTINCT, FALSE, FROM, IS, NOT, NULL, OR, SELECT, TRUE, WHERE,
    COMA, SEMICOLON, DOT, LEFT_PAREN, RIGHT_PAREN,
    LT, LE, GT, GE, EQUAL, NE,
    PLUS, MINUS, STAR, SLASH,
    EOF
}
